config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
    @products = Product.find(params[:id])

  end

  def new
  	@product = Product.new
  	
  end

  def create
    @product = Product.new(product_params)
  	if @product.save
  		redirect_to  root_path, notice: "Successfully created a Product"
  	end
  end
  

  def edit
    @product = Product.find(params[:id])
  end

  def update
  		@product = Product.find(params[:id])
    	if @product.update!(product_params)
    	 redirect_to root_path, notice: "Successfully Updated a Product"
      end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_url, notice: "Product Destruction Completed"

  end
  def product_params    
    params.require(:product).permit(:name,:description, :price, :published)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Niels First Awesome Rails Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.number_field :price %>
  <%= f.check_box :published%>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1>All the Products</h1>
<h3>Adding a Product?</h3>
<p>Click on The link that I am going to give you</p>
<p>When I figure out...</p>
<p>The Link Tag in Rails...</p>

<%= link_to "CLICK HERE", new_product_path  %>

<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Price</th>
		<th>Published</th>
		<th>edit</th>
		<th>delete</th>
	</tr>
	<%  @products.each do |product| %> 
	<tr>
		<td><%= product.name %></td>
		<td><%= product.description %></td>
		<td><%= product.price %></td>
		<td><%= product.published %></td>
		<td><%= link_to "edit", edit_product_path(product) %> </td>
		<td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %> 
	 	
</table>

app/views/products/new.html.erb
<%= form_for :product, url: products_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :price %>
  <%= f.number_field :price %><br>
  <%= f.label :published %>
  <%= f.check_box :published%><br>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1> this is show </h1>


<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Price</th>
		<th>Published</th>
	</tr>
	
	<tr>
		<td><%= @products.name %></td>
		<td><%= @products.description %></td>
		<td><%= @products.price %></td>
		<td><%= @products.published %></td>
	</tr>

	<h1>If you are ready to edit this click <%= link_to "here", edit_product_path  %></h1>
	
	 	
</table>
		

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>